# Uma pequena introdução ao python


O python é uma linguagem interpretada, ou seja, ao invés de gerar um executável, um programa, chamado de interpretador lê o script em tempo real e executa cada instrução a seu devido tempo. Isso gera uma vantagem em relação à portabilidade, já que o mesmo script, em tese pode ser lido por máquinas diferentes que tenham seu interpretador python. 

O python também é uma linguagem de alto-nível, ou seja, aceita um grau de abstração maior e é mais amigável ao programador. 
Essas vantagens obviamente não são isentas de sacrifícios, como por exemplo maior necessidade de recursos de tempo e memória. A linguagem também é conhecida por ter seus loops lentos o que, ironicamente, a torna menos atraente para a técnica abordada neste curso.

Por razões didáticas, usaremos o python mesmo assim, além disso os problemas que serão tratados aqui são pequenos e portanto as deficiências do python não se tornarão evidentes. Dito isso, vamos começar este minicurso.

## Importando outros módulos
Os scripts do python são escritos em móduios e sua extensão é .py . É possível importar funções, classes e variáveis de outros módulos usando o comando *import*. No exemplo abaixo estamos importando o módulo numpy, um módulo importante que facilita muito o trabalho com matrizes e arrays. 

In [1]:
import numpy as np

test_array =  np.array([
    [0,1,0],
    [0,0,1],
    [0,0,1]
])

print(test_array)

[[0 1 0]
 [0 0 1]
 [0 0 1]]


No trecho acima importamos o módulo numpy e usamos a palavra chave *as* para dizer que iremos nos referir à esse módulo como *np*, ao invés de usar seu nome completo. 

Em seguida criamos uma estrutura do tipo array, que é própria do módulo numpy e chamamos tal estrutura de "test_array". Observe que antes da classe array temos o prefixo *np.*, ou seja, estamos dizendo para o interpretador python que ele vai encontrar as informações da classe array dentro do módulo numpy.

Por fim, nós mandamos imprimir a array que criamos, usando a função *print*

## Variáveis e estruturas de dados

O python possui diversos tipos de variávies, como inteiras, string, de ponto flutuante entre outras. Para ele, elas são como objetos e o interpretador aloca a memória de acordo com a necessidade, portanto não é necessário declarar o tipo da variável, alocar memória manualmente para estruturas de dados, ou mesmo criar um ponteiro para o início das mesmas. Variáveis também podem mudar de tipo durante a execução de um programa sem grande problema, tal qual no exemplo abaixo:

In [4]:
teste_var = 10
print(type(teste_var))

teste_var = 10.5
print(type(teste_var))

teste_var = '10.5'
print(type(teste_var))

<class 'int'>
<class 'float'>
<class 'str'>


Usando a função *type* pudemos verificar que a variável teste_var mudou entre os tipos inteiro (int), ponto flutuante (float) e string (str). 

Variáveis podem ser nomeadas usando qualquer usando qualquer letra, seja em caixa alta, ou baixa, digito, ou o caracter " _ ". Elas também não podem começar com um digito. Todavia, o pep8, a convenção de estilo do python, estipula que se deve usar o método letras minúsculas e palavras separadas por " _ " para nomear variáveis. 

O python não faz distinção entre as variáveis anteriores e estruturas de dados como listas, conjuntos e dicionários. Para a CGP, listas e dicionários são estruturas interessantes e a seguir temos o exemplo de ambos:

In [1]:
exemplo_lista = [1,2,10,2,15,20]
exemplo_lista2 = ['a','b','teste']
exemplo_lista3 = [10,'olá',15.3]

exemplo_dic = {'verde':'limão','vermelho':'maçã'}
exemplo_dic2 = {0:'wire', 1:'not', 2:'and'}