# Uma pequena introdução ao python


O python é uma linguagem interpretada, ou seja, ao invés de gerar um executável, um programa, chamado de interpretador lê o script em tempo real e executa cada instrução a seu devido tempo. Isso gera uma vantagem em relação à portabilidade, já que o mesmo script, em tese pode ser lido por máquinas diferentes que tenham seu interpretador python. 

O python também é uma linguagem de alto-nível, ou seja, aceita um grau de abstração maior e é mais amigável ao programador. 
Essas vantagens obviamente não são isentas de sacrifícios, como por exemplo maior necessidade de recursos de tempo e memória. A linguagem também é conhecida por ter seus loops lentos o que, ironicamente, a torna menos atraente para a técnica abordada neste curso.

Por razões didáticas, usaremos o python mesmo assim, além disso os problemas que serão tratados aqui são pequenos e portanto as deficiências do python não se tornarão evidentes. Dito isso, vamos começar este minicurso.

## Importando outros módulos
Os scripts do python são escritos em móduios e sua extensão é .py . É possível importar funções, classes e variáveis de outros módulos usando o comando *import*. No exemplo abaixo estamos importando o módulo numpy, um módulo importante que facilita muito o trabalho com matrizes e arrays. 

In [2]:
import numpy as np

test_array =  np.array([
    [0,1,0],
    [0,0,1],
    [0,0,1]
])

print(test_array)

[[0 1 0]
 [0 0 1]
 [0 0 1]]


No trecho acima importamos o módulo numpy e usamos a palavra chave *as* para dizer que iremos nos referir à esse módulo como *np*, ao invés de usar seu nome completo. 

Em seguida criamos uma estrutura do tipo array, que é própria do módulo numpy e chamamos tal estrutura de "test_array". Observe que antes da classe array temos o prefixo *np.*, ou seja, estamos dizendo para o interpretador python que ele vai encontrar as informações da classe array dentro do módulo numpy.

Por fim, nós mandamos imprimir a array que criamos, usando a função *print*

## Variáveis e estruturas de dados

O python possui diversos tipos de variávies, como inteiras, string, de ponto flutuante entre outras. Para ele, elas são como objetos e o interpretador aloca a memória de acordo com a necessidade, portanto não é necessário declarar o tipo da variável, alocar memória manualmente para estruturas de dados, ou mesmo criar um ponteiro para o início das mesmas. Variáveis também podem mudar de tipo durante a execução de um programa sem grande problema, tal qual no exemplo abaixo:

In [3]:
teste_var = 10
print(type(teste_var))

teste_var = 10.5
print(type(teste_var))

teste_var = '10.5'
print(type(teste_var))

<class 'int'>
<class 'float'>
<class 'str'>


Usando a função *type* pudemos verificar que a variável teste_var mudou entre os tipos inteiro (int), ponto flutuante (float) e string (str). 

Variáveis podem ser nomeadas usando qualquer usando qualquer letra, seja em caixa alta, ou baixa, digito, ou o caracter " _ ". Elas também não podem começar com um digito. Todavia, o pep8, a convenção de estilo do python, estipula que se deve usar o método letras minúsculas e palavras separadas por " _ " para nomear variáveis. 

O python não faz distinção entre as variáveis anteriores e estruturas de dados como listas, conjuntos e dicionários. Para a CGP, listas e dicionários são estruturas interessantes e a seguir temos o exemplo de ambos:

In [4]:
exemplo_lista = [1,2,10,2,15,20]
exemplo_lista2 = ['a','b','teste']
exemplo_lista3 = [10,'olá',15.3,[1,5,10,21]]

exemplo_dic = {'verde':'limão','vermelho':'maçã'}
exemplo_dic2 = {0:'wire', 1:'not', 2:'and'}

Não cabe aqui passar as definição clássica de lista, o que é interessante dizer é que no python as listas tem seus índices associados a uma array. Ou seja, enquanto em uma lista simples a complexidade para acessar um determinado indice i é O(i), no python vai ser O(1). Cada elemento também pode ser de qualquer outra classe do python, você pode ter listas contendo inteiros e ao mesmo tempo float, stings, outras listas e até mesmo funções.

Os elementos em uma lista são numerados de 0 a n-1 sendo n a quantidade de elementos na lista. Para acessar um determinado elemento da lista basta usar o nome dela e colocar o índice do elemento entre chaves. É possível usar índices negativos para acessar elementos à partir do final.

É possível selecionar um setor de uma lista usando o ":".



In [5]:
#elementos individuais
print(exemplo_lista[2])
print(exemplo_lista2[2])
#indices negativos
print(exemplo_lista3[-1])
#listas em listas
print(exemplo_lista3[-1][0])
#a mesma lógica funciona para strings
print(exemplo_lista2[2][3])
#Selecionando setores
print(exemplo_lista[:3]) #do inicio até, porém não incluindo, o elemento de indice 3
print(exemplo_lista[3:]) #do elementos de índice 3 até o final
print(exemplo_lista[1:-1]) #do primeiro elemento até o penultimo

10
teste
[1, 5, 10, 21]
1
t
[1, 2, 10]
[2, 15, 20]
[2, 10, 2, 15]


É possível substituir elementos em uma lista: basta acessar o elemento em questão e associar um novo valor. Isso vale para trechos também, porém é importante que as dimensões dos valores sejam as mesmas, ou seja, um trecho de 5 elementos tem que ser substituido por outros 5 elementos.

Para adicionar novos valores na lista, usualmente se usa o método append. Para remover basta usar o método remove. Em ambos você escreve o nome da lista em questão seguidos por .nome_do_método(). O método remove vai remover a primeira ocorrência do valor na lista, o método append vai inserir o valor no final da lista.

In [6]:
n_lista = [] #criamos uma lista vazia
n_lista.append(1)
n_lista.append(2)
n_lista.append(3)
n_lista.append(2)
n_lista.append(5)
n_lista.append(2) #inserimos, nessa ordem: 1,2,3,2,5,2
print(n_lista)
n_lista.remove(2) #vai remover o primeiro 2 de n_lista, ou seja o entre o 1 e 3
print(n_lista)
n_lista[1]=-3 #substitui o valor na posição 1 por -3
n_lista.append(7) #vai inserir um 7 no final da lista, resultando em 1,-3,2,5,2,7
print(n_lista)

[1, 2, 3, 2, 5, 2]
[1, 3, 2, 5, 2]
[1, -3, 2, 5, 2, 7]


Os dicionários são estruturas contendo dois itens, as chaves (dict.keys) e os valores (dict.values). As chaves são os "índices" dos dicionários e cada chave deve ser única e cada qual tem um valor associado. Tal qual a lista, os valores podem ser de qualquer tipo, inclusive outros dicionários.

O método keys mostra as chaves do dicionário enquanto o método values mosta uma lista com todos os valores.

Para selecionar um valor, basta colocar a chave do valor entre [] após o nome do dicionário.

Para modificar o valor de uma chave é só usar a operação de atribuição para a mesma.

Para criar um novo par chave:valor, basta usar a operação de atribuição usando a nova chave e o novo valor.

In [7]:
print(exemplo_dic.keys()) #as chaves do exemplo_dic
print(exemplo_dic.values()) #os valores do exemplo_dic
print(exemplo_dic['verde']) #O valor atribuido à chave verde
exemplo_dic['verde'] = ['limão','abacate'] #substituindo o antigo valor da chave verde por uma lista com duas frutas verdes
print(exemplo_dic['verde'])
exemplo_dic['roxo'] = ['uva','ameixa'] #criando um novo conjunto chave:valor
print(exemplo_dic.keys())
print(exemplo_dic.values())

dict_keys(['verde', 'vermelho'])
dict_values(['limão', 'maçã'])
limão
['limão', 'abacate']
dict_keys(['verde', 'vermelho', 'roxo'])
dict_values([['limão', 'abacate'], 'maçã', ['uva', 'ameixa']])


As variáveis que você atribui à listas e dicionários na verdade armazenam um ponteiro para essas estruturas. Por isso fazer uma cópia das mesmas não é uma tarefa simples e requer algum cuidado.

In [8]:
c_lista = n_lista
print(n_lista)
c_lista.append(2)
print(n_lista)

[1, -3, 2, 5, 2, 7]
[1, -3, 2, 5, 2, 7, 2]


No exemplo anterior atribuimos o que estava armazenado em n_lista (um ponteiro para uma lista) para c_lista. Ao modificarmos c_lista, acabamos modificando n_lista também. Para evitar que isso aconteça, temos que usar o método copy().

In [9]:
c_lista = n_lista.copy()
print(n_lista)
c_lista.append(9)
print(n_lista)
print(c_lista)

[1, -3, 2, 5, 2, 7, 2]
[1, -3, 2, 5, 2, 7, 2]
[1, -3, 2, 5, 2, 7, 2, 9]


O método copy copia os valores da lista, dicionário para outro setor da memória e cria um novo ponteiro para essa região. Note que isso só afeta a lista, ou o dicionário em questão! 

Por exemplo, se temos uma lista:
a = \[ 1,2 \[ 'a','b','c'\], 12, 'c'\]

O elemento 2 é na verdade um ponteiro para uma lista e portanto o método a.copy() copiara esse ponteiro para o elemento 2 da nova lista b. Uma alteração no elemento 2 de b, como um todo, não causará alteração em a. Mas uma modificação em nível lista do elemento 2 de b, causará uma alteração em a. O exemplo abaixo ilustra isso melhor:

In [10]:
a = [1,2,['a','b','c'],12,'c']
b = a.copy()
c = a.copy()
b[2] = 10
print('lista b:',b)
print('lista a:',a)
c[2].append('d')
print('lista c:',c)
print('lista a:',a)


lista b: [1, 2, 10, 12, 'c']
lista a: [1, 2, ['a', 'b', 'c'], 12, 'c']
lista c: [1, 2, ['a', 'b', 'c', 'd'], 12, 'c']
lista a: [1, 2, ['a', 'b', 'c', 'd'], 12, 'c']


Testes lógicos e desvios condicionais são feitos com as palavras if, elif e else. O if é o teste principal, o elif é um novo teste caso o teste anterior tenha dado falso e o else é caso todos os testes anteriores tenham dado falso. 

O python não usa parenteses ou chaves para limitar seus blocos de instrução, é possível escrever if, seguidos do teste lógico seguido de : para indicar o teste. As instruções dentro do bloco referente à esse if são reconhecidas por uma indentação, no caso 4 espaços à frente em relação à coluna do bloco.

In [11]:
var_alpha = 10
var_beta = 'C17_design'
var_delta = [1,.9,.2,.8,.5]

if var_alpha > 10:
    print('alpha maior que 10')

if '_design' in var_beta:
    print('Experimento de design')
    budget = 3000
else:
    print('Experimento de otimização')
    budget = 60000

if 2 in var_delta:
    print('2 está em Delta')
elif np.max(var_delta) > 2:
    print('delta extrapolou 2')
elif np.max(var_delta) > 1.8:
    print('delta próximo de 2')
else:
    print('2 não está em Delta')

Experimento de design
2 não está em Delta


A mesma lógica segue para o ciclo while, onde você tem um teste lógico e o ciclo é executado enquanto o teste for verdadeiro.

In [12]:
value = 0
while value < 3:
    value = np.random.randint(6)
    print(value)

5


No python, o ciclo for pecorre um objeto iterável. Para se ter um ciclo incremental ou decremental igual ao normalmente usado em C, pode-se usar a função range:

In [13]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


Para funções, usa-se a palavra chave def. Como já foi dito, não há necessidade de se declarar os tipos de variáveis no escopo.

Algumas variáveis podem ser opcionais e elas vão no final do escopo da função, com seus respectivos valores padrões.

A palavra chave return informa os valores de saída da função.

In [16]:
def normalize(values, o_top = False):
    res = []
    
    mx_val = np.max(values)
    if o_top:
        mn_val = 0
    else:
        mn_val = np.min(values)
    delta = mx_val- mn_val
    for i in values:
        res.append((i - mn_val)/delta)
    return res

list_a = [1,3,4,11,12,13,16,17,19,26]

print(normalize(list_a))
print(normalize(list_a, True))

[0.0, 0.08, 0.12, 0.4, 0.44, 0.48, 0.6, 0.64, 0.72, 1.0]
[0.038461538461538464, 0.11538461538461539, 0.15384615384615385, 0.4230769230769231, 0.46153846153846156, 0.5, 0.6153846153846154, 0.6538461538461539, 0.7307692307692307, 1.0]
